import { Header } from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "../styles/globals.css";

import dayjs from "dayjs";
import "dayjs/locale/pt-br";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.locale("pt-br");
dayjs.extend(relativeTime);

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR">
			<body className={GeistSans.className}>
				<Header />
				{children}

				<Toaster />
			</body>
		</html>
	);
}
