import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="grid grid-cols-2 min-h-screen">
			<div className="bg-accent-foreground">a</div>
			<div>{children}</div>
		</div>
	);
}
