import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="grid grid-cols-2">
			<div className="bg-accent-foreground max-h-[calc(100vh-56px)]">a</div>
			<div className="max-h-[calc(100vh-56px)] h-screen pb-8">{children}</div>
		</div>
	);
}
